---
- name: Generate Rulebook Activations for team-defined rulebooks
  hosts: all
  connection: local
  vars:
    _team_rulebook_git_repo: "https://github.com/derekwaters/eda-multitenant-team.git"
    _team_rulebook_exclude_list: "rulebook_template.yaml"
    _team_rulebook_tmp_dir: "/tmp/checkout"
    kafkahostname: "something"
    kafkaport: 9192
    kafkagroupid: "eda"

  
  tasks:
    - name: Pull the git repo with the rulebooks
      ansible.builtin.git:
        repo: "{{ _team_rulebook_git_repo }}"
        dest: "{{ _team_rulebook_tmp_dir }}"
        single_branch: yes
        version: main

    - name: Iterate over the team rulebooks to build list of rulebooks
      ansible.builtin.find:
        paths: "{{ _team_rulebook_tmp_dir }}"
        patterns: "*.yaml,*.yml"
        excludes: "{{ _team_rulebook_exclude_list }}"
      register: _rulebook_files
        
    - name: Generate the rulebook filenames
      ansible.builtin.set_fact:
        _rulebook_filenames: "{{ _rulebook_filenames | default([]) + [ item.path | basename ]}}"
      loop: "{{ _rulebook_files.files }}"

    - name: Generate rulebook activations data
      ansible.builtin.set_fact:
        _activations: >
          "{{ _activations | default([]) + [ {
            'name': rulebook, 
            'description': 'Activation for ' + rulebook,
            'project': 'eda-multitenant-team',
            'rulebook': rulebook,
            'decision_environment': 'Default Decision Environment',
            'extra_vars': {
              'kafkahostname': kafkahostname,
              'kafkaport': kafkaport,
              'kafkagroupid': kafkagroupid
            },
            'enabled': true,
            'state': 'present'
          } ] }}"
      loop: "{{ _rulebook_filenames }}"
      loop_control:
        loop_var: rulebook
        
    - name: Dump the activation data
      ansible.builtin.debug:
        var: _activations

    - name: Make the activations object
      ansible.builtin.set_fact:
        eda_rulebook_activations: "{{ _activations | from_json }}"

    - name: Dump the activation data
      ansible.builtin.debug:
        var: eda_rulebook_activations

    - name: Create the Rulebook Activation objects
      ansible.builtin.include_role:
        name: "infra.eda_configuration.rulebook_activation"

    - name: Clean up
      ansible.builtin.file:
        path: "{{ _team_rulebook_tmp_dir }}"
        state: absent